"""empty message

Revision ID: 8df8bcbf6306
Revises: 20c5180f2ccc
Create Date: 2020-10-15 21:17:55.649421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8df8bcbf6306'
down_revision = '20c5180f2ccc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('city', sa.String(), nullable=True))
    op.drop_column('customers', 'area')
    op.add_column('providers', sa.Column('city', sa.String(), nullable=True))
    op.drop_column('providers', 'area')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('area', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('providers', 'city')
    op.add_column('customers', sa.Column('area', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('customers', 'city')
    # ### end Alembic commands ###
